name: image
on:
  push:
    branches:
      - 'master'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: publish
        run: |
          export GIT_VERSION=$(git describe --always --tags)
          export IMAGE_TAG?=$(GIT_VERSION)
          docker build --file Dockerfile --progress plane --tag ghcr.io/${{ github.repository }}:$(IMAGE_TAG) --cache-from ghcr.io/${{ github.repository }}:latest .
          docker build --file Dockerfile --progress plane --push --tag ghcr.io/${{ github.repository }} --cache-from ghcr.io/${{ github.repository }}:latest .
          docker build --file Dockerfile --progress plane --push --tag ghcr.io/${{ github.repository }} --cache-from ghcr.io/${{ github.repository }}:$(IMAGE_TAG) .